
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team02-s24-5pm-7
owner: ucsb-cs156-s24
repo_name: team02-s24-5pm-7
pull_requests: [{"author":{"id":"U_kgDOBbiZfw","is_bot":false,"login":"aneeshtheplug","name":""},"headRefName":"aneesh-UCSBOrgsTable","number":59,"title":"Aneesh ucsb orgs ","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-7/pull/59"},{"author":{"id":"U_kgDOBtP22A","is_bot":false,"login":"katelarrick","name":""},"headRefName":"Kate-MenuItemsController","number":58,"title":"Kate Menu Items Controller + Tests","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-7/pull/58"},{"author":{"id":"U_kgDOBh2uuQ","is_bot":false,"login":"adilahmed2","name":"Adil Ahmed"},"headRefName":"Adil-RecommendationRequests","number":54,"title":"Adil Recommendation Requests PR","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-7/pull/54"},{"author":{"id":"U_kgDOBnFUwg","is_bot":false,"login":"zhenbi93","name":""},"headRefName":"June-Articles-Get","number":51,"title":"Add Get ENDPOINT in Articles Controller","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-7/pull/51"},{"author":{"id":"U_kgDOBnFUwg","is_bot":false,"login":"zhenbi93","name":""},"headRefName":"June-Articles-Delete","number":50,"title":"June articles delete","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-7/pull/50"},{"author":{"id":"U_kgDOBnFUwg","is_bot":false,"login":"zhenbi93","name":""},"headRefName":"June-Article-Controller","number":49,"title":"June article controller","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-7/pull/49"},{"author":{"id":"U_kgDOBnFUwg","is_bot":false,"login":"zhenbi93","name":""},"headRefName":"June-Article","number":48,"title":"June Create database Table for Articles","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-7/pull/48"},{"author":{"id":"U_kgDOBtKOXg","is_bot":false,"login":"gracefeng05","name":""},"headRefName":"Grace-HelpRequestGetEndpoint","number":47,"title":"Add Help Request GET Endpoint for Single Record","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-7/pull/47"},{"author":{"id":"U_kgDOBtKOXg","is_bot":false,"login":"gracefeng05","name":""},"headRefName":"Grace-HelpRequestPutEndpoint","number":46,"title":"Added Help Request PUT Endpoint and Testing","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-7/pull/46"}]
