
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team02-s24-5pm-7
owner: ucsb-cs156-s24
repo_name: team02-s24-5pm-7
pull_requests: [{"author":{"id":"U_kgDOBXvwJA","is_bot":false,"login":"koraykondakci","name":""},"headRefName":"kk-MenuItemReview-create-db","number":63,"title":"Created database table for Menu Item Review","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-7/pull/63"},{"author":{"id":"U_kgDOBtP22A","is_bot":false,"login":"katelarrick","name":""},"headRefName":"Kate-MenuItemsController","number":58,"title":"Kate Menu Items Controller + Tests","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-7/pull/58"},{"author":{"id":"U_kgDOBtKOXg","is_bot":false,"login":"gracefeng05","name":""},"headRefName":"Grace-HelpRequestGetEndpoint","number":47,"title":"Add Help Request GET Endpoint for Single Record","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-7/pull/47"}]
