
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team02-s24-5pm-7
owner: ucsb-cs156-s24
repo_name: team02-s24-5pm-7
pull_requests: [{"author":{"id":"U_kgDOBnFUwg","is_bot":false,"login":"zhenbi93","name":""},"headRefName":"June-Article-Controller","number":49,"title":"June article controller","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-7/pull/49"},{"author":{"id":"U_kgDOBnFUwg","is_bot":false,"login":"zhenbi93","name":""},"headRefName":"June-Article","number":48,"title":"June Create database Table for Articles","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-7/pull/48"},{"author":{"id":"U_kgDOBtKOXg","is_bot":false,"login":"gracefeng05","name":""},"headRefName":"Grace-HelpRequestGetEndpoint","number":47,"title":"Add Help Request GET Endpoint for Single Record","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-7/pull/47"},{"author":{"id":"U_kgDOBtKOXg","is_bot":false,"login":"gracefeng05","name":""},"headRefName":"Grace-HelpRequestPutEndpoint","number":46,"title":"Added Help Request PUT Endpoint and Testing","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-7/pull/46"},{"author":{"id":"U_kgDOBtKOXg","is_bot":false,"login":"gracefeng05","name":""},"headRefName":"Grace-HelpRequestDeleteEndpoint","number":45,"title":"Add Help Request DELETE Endpoint + Testing","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-7/pull/45"},{"author":{"id":"U_kgDOBtKOXg","is_bot":false,"login":"gracefeng05","name":""},"headRefName":"Grace-HelpRequestController","number":44,"title":"Create Help Request controller with GET + POST methods and testing","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-7/pull/44"},{"author":{"id":"U_kgDOBtKOXg","is_bot":false,"login":"gracefeng05","name":""},"headRefName":"Grace-HelpRequestTable","number":43,"title":"Created database table for Help Request","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-7/pull/43"}]
